### ISSUE TITLE
UnhandledPromiseRejectionWarning thrown from this module

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-utils#3]
```console
(node:19077) UnhandledPromiseRejectionWarning: Error: invalid ip
    at module.exports (/Users/alex/.nvm/versions/node/v10.17.0/lib/node_modules/ipfs/node_modules/libp2p-utils/src/ip-port-to-multiaddr.js:8:11)
    at module.exports (/Users/alex/.nvm/versions/node/v10.17.0/lib/node_modules/ipfs/node_modules/libp2p-tcp/src/socket-to-conn.js:55:39)
    at Server.net.createServer (/Users/alex/.nvm/versions/node/v10.17.0/lib/node_modules/ipfs/node_modules/libp2p-tcp/src/listener.js:23:20)
    at Server.emit (events.js:198:13)
    at TCP.onconnection (net.js:1520:8)
```

This can cause applications to crash.

**Comment by vasco-santos** [comment]
@achingbrain this module throws when parameters are not valid, which seems correct to me.  who uses this module (`libp2p-tcp` in this case) should take this into account, right?

**Comment by achingbrain** [comment]
https://github.com/libp2p/js-libp2p-tcp/issues/121

**Comment by jacobheun** [comment]
@vasco-santos while tcp needs to catch this we should improve the errors in this function to include the ip and port that were provided to more easily diagnose these issues. I'm assuming this is an issue with the remote address being a DNS or similar address, but can't be certain due to the lack of info in the logs.

**Comment by vasco-santos** [comment]
Yeah, that seems a good call! I can add them to the errors
